select PH.POSITION_ID,
(SELECT POSITION_NAME FROM "MDB_DEV"."MST_POSITION" WHERE POSITION_ID=PH.POSITION_ID) AS POS_NAME
,E.POSITION_VALUE_ID from "MDB_DEV"."MST_EMPLOYEE" AS E
JOIN "MDB_DEV"."MAP_ROLE_POSITION" AS RP ON RP.ROLE_POS_ID=E.ROLE_POSITION_ID 
JOIN "MDB_DEV"."MST_POSITION" AS P ON P.POSITION_ID=RP.POSITION_ID
JOIN "MDB_DEV"."POSITION_HIERARCHY" AS PH ON PH.PARENT_POSITION_ID=P.POSITION_ID
WHERE EMPLOYEE_CODE='EMP402018' AND PH.PARENT_POSITION_ID!=PH.POSITION_ID

IND

SELECT * FROM "MDB_DEV"."MST_REGION" WHERE COUNTRY_CODE='IND'
NE,SW
SELECT * FROM "MDB_DEV"."MST_EMPLOYEE" WHERE POSITION_VALUE_ID IN ('NE','SW')
EMP352018,EMP412018

select DISTINCT PH.POSITION_ID,
(SELECT POSITION_NAME FROM "MDB_DEV"."MST_POSITION" WHERE POSITION_ID=PH.POSITION_ID) AS POS_NAME
,E.POSITION_VALUE_ID from "MDB_DEV"."MST_EMPLOYEE" AS E
JOIN "MDB_DEV"."MAP_ROLE_POSITION" AS RP ON RP.ROLE_POS_ID=E.ROLE_POSITION_ID 
JOIN "MDB_DEV"."MST_POSITION" AS P ON P.POSITION_ID=RP.POSITION_ID
JOIN "MDB_DEV"."POSITION_HIERARCHY" AS PH ON PH.PARENT_POSITION_ID=P.POSITION_ID
WHERE EMPLOYEE_CODE IN ('EMP352018','EMP412018') AND PH.PARENT_POSITION_ID!=PH.POSITION_ID

SELECT * FROM "MDB_DEV"."MST_STATE" WHERE REGION_CODE in ('NE','SW')
'UP','AP','AR'

SELECT * FROM "MDB_DEV"."MST_EMPLOYEE" WHERE POSITION_VALUE_ID IN ('UP','AP','AR')
'EMP422018','EMP392018','EMP362018'

select DISTINCT PH.POSITION_ID,
(SELECT POSITION_NAME FROM "MDB_DEV"."MST_POSITION" WHERE POSITION_ID=PH.POSITION_ID) AS POS_NAME
,E.POSITION_VALUE_ID from "MDB_DEV"."MST_EMPLOYEE" AS E
JOIN "MDB_DEV"."MAP_ROLE_POSITION" AS RP ON RP.ROLE_POS_ID=E.ROLE_POSITION_ID 
JOIN "MDB_DEV"."MST_POSITION" AS P ON P.POSITION_ID=RP.POSITION_ID
JOIN "MDB_DEV"."POSITION_HIERARCHY" AS PH ON PH.PARENT_POSITION_ID=P.POSITION_ID
WHERE EMPLOYEE_CODE IN ('EMP422018','EMP392018','EMP362018') AND PH.PARENT_POSITION_ID!=PH.POSITION_ID





